# SPDX-FileCopyrightText: Elias Mueller
#
# SPDX-License-Identifier: MIT

name: Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - name: Install just
        uses: taiki-e/install-action@41049aa56687c35e0afa74eed4f09cec4f9afabf # v2.85.2
        with:
          tool: just
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: false
      - name: Install libEGL for PySide6
        run: sudo apt-get update && sudo apt-get install -y libegl1
      - name: Run pre-commit hooks
        run: just fmt
        env:
          SKIP: qmllint
      - name: Run the QML tests
        run: just test
      - name: Run the Python tests
        run: just test-python
      - name: Verify REUSE compliance
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6
